# Generated by Django 4.1.1 on 2022-10-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_alter_user_avg_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
