# Generated by Django 4.1.1 on 2022-10-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_alter_city_lat_alter_city_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name='city',
            name='lng',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
    ]
