# Generated by Django 4.1.1 on 2022-10-12 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('cities', '0001_init_models'),
        ('vehicles', '0001_init_models'),
        ('users', '0001_init_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('ride_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_from', models.CharField(max_length=100)),
                ('area_to', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seats', models.IntegerField()),
                ('recurrent', models.BooleanField(default=False)),
                ('automatic_confirm', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('city_from',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_from',
                                   to='cities.city')),
                ('city_to',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_to',
                                   to='cities.city')),
                ('driver',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver',
                                   to='users.user')),
                ('passengers', models.ManyToManyField(blank=True, related_name='passenger', to='users.user')),
                ('vehicle',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ride',
                                   to='vehicles.vehicle')),
            ],
        ),
    ]
