# Generated by Django 4.1.1 on 2022-11-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='was_archived',
            field=models.BooleanField(default=False),
        ),
    ]
