# Generated by Django 4.1.1 on 2022-10-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='available_seats',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
