# Generated by Django 4.1.1 on 2022-10-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rides', '0002_ride_available_seats_ride_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='available_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
