# Generated by Django 4.1.1 on 2022-10-15 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rides', '0003_alter_ride_available_seats_alter_ride_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='ride',
            name='duration',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
