# Generated by Django 4.1.1 on 2022-10-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_remove_ride_end_date_alter_ride_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='available_seats',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='seats',
            field=models.PositiveIntegerField(),
        ),
    ]
