# Generated by Django 4.1.1 on 2022-10-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_alter_ride_available_seats_participation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='area_from',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ride',
            name='area_to',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ride',
            name='available_seats',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
