# Generated by Django 4.1.1 on 2022-10-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0008_alter_participation_user_alter_ride_passengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='available_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
