# Generated by Django 4.1.1 on 2022-10-21 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0010_alter_ride_area_from_alter_ride_area_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('coordinate_id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=15)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=15)),
                ('sequence_no', models.IntegerField()),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='rides.ride')),
            ],
        ),
    ]
