# Generated by Django 4.1.1 on 2022-10-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0011_coordinate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='decision',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='pending', max_length=9),
        ),
    ]
