# Generated by Django 4.1.1 on 2022-10-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0012_alter_participation_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
