# Generated by Django 4.1.1 on 2022-10-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0013_ride_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='reserved_seats',
            field=models.IntegerField(default=1),
        ),
    ]
