# Generated by Django 4.1.1 on 2022-10-31 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0015_recurrentride_ride_recurrent_ride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='recurrent_ride',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='single_rides', to='rides.recurrentride'),
        ),
    ]
