# Generated by Django 4.1.1 on 2022-11-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0015_recurrentride_ride_recurrent_ride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrentride',
            name='frequency_type',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=9),
        ),
    ]
