# Generated by Django 4.1.1 on 2022-11-01 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0017_alter_ride_recurrent_ride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='ride',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='rides.ride'),
        ),
    ]
