# Generated by Django 4.1.1 on 2022-11-03 17:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0017_alter_recurrentride_occurrences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrentride',
            name='occurrences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=10), blank=True, null=True, size=None),
        ),
    ]
