# Generated by Django 4.1.1 on 2022-10-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
    ]
